// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package com.anuj.edh.oct.scalaxb

/**
			Copyright 2018 IBS Software Private Limited. All Rights Reserved.
			This document is the proprietary information of IBS Software Services Private Limited. Use is subject to license terms.		
		
*/


case class MetaData(attributes: Map[String, scalaxb.DataRecord[Any]] = Map.empty) {
  lazy val schemaVersion = attributes("@schemaVersion").as[Float]
}

      

sealed trait ActionTypes

object ActionTypes {
  def fromString(value: String, scope: scala.xml.NamespaceBinding)(implicit fmt: scalaxb.XMLFormat[ActionTypes]): ActionTypes = fmt.reads(scala.xml.Text(value), Nil) match {
    case Right(x: ActionTypes) => x
    case x => throw new RuntimeException(s"fromString returned unexpected value $x for input $value")
  }
  lazy val values: Seq[ActionTypes] = Seq(ACKNOWLEDGE, CREATE, DELETE, END, GET, START, UPDATE)
}

case object ACKNOWLEDGE extends ActionTypes { override def toString = "ACKNOWLEDGE" }
case object CREATE extends ActionTypes { override def toString = "CREATE" }
case object DELETE extends ActionTypes { override def toString = "DELETE" }
case object END extends ActionTypes { override def toString = "END" }
case object GET extends ActionTypes { override def toString = "GET" }
case object START extends ActionTypes { override def toString = "START" }
case object UPDATE extends ActionTypes { override def toString = "UPDATE" }


/** General message attributes
*/
case class MessageAttributes(actionType: Option[ActionTypes] = None,
  messageReference: Option[String] = None,
  batchReference: Option[String] = None,
  sequenceNumber: Option[Int] = None,
  batchEndInd: Option[Boolean] = None,
  timestamp: javax.xml.datatype.XMLGregorianCalendar,
  originator: Option[String] = None,
  proprietaryNotice: String,
  company: Option[String] = None,
  tenant: Option[String] = None)

